services:
  app:
    build: .
    container_name: app
    command: bash -c "cd app && poetry run alembic upgrade head && poetry run python3 main.py"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=postgresql
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=ragnarok-bro-api
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
