services:
  app:
    build: .
    container_name: app
    command: bash -c "cd app && poetry run alembic upgrade head && poetry run python3 main.py"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=postgresql
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=ragnarok-bro-api
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  test_postgresql:
    image: postgres
    container_name: test_postgresql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=test-ragnarok-bro-api

  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    depends_on:
      - app
      - postgresql

  web_scraping:
    build: .
    container_name: web_scraping
    command: "poetry run python3 web_scraping/main.py"
    environment:
      - APP_URL=app
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - app
      - postgresql
      - selenium
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ragnarok.com
      PGADMIN_DEFAULT_PASSWORD: 123@password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
