"""Add weapons

Revision ID: 07b518539437
Revises: 2d9097bc6c53
Create Date: 2023-12-09 18:08:27.644260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b518539437'
down_revision: Union[str, None] = '2d9097bc6c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weapons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('thrown_on_the_floor', sa.Boolean(), nullable=True),
    sa.Column('negotiated', sa.Boolean(), nullable=True),
    sa.Column('placed_in_the_warehouse', sa.Boolean(), nullable=True),
    sa.Column('stored_in_cart', sa.Boolean(), nullable=True),
    sa.Column('sold_to_npc', sa.Boolean(), nullable=True),
    sa.Column('placed_in_the_guild_warehouse', sa.Boolean(), nullable=True),
    sa.Column('drop_from_monster_id', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('obtained_from_id', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weapons_id'), 'weapons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weapons_id'), table_name='weapons')
    op.drop_table('weapons')
    # ### end Alembic commands ###
