"""Add img_url to monsters

Revision ID: 0d0d9337be00
Revises: 06d07f4303d8
Create Date: 2023-12-10 12:00:37.132110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d0d9337be00'
down_revision: Union[str, None] = '06d07f4303d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monsters', 'img_url')
    # ### end Alembic commands ###
