"""Add items and monsters

Revision ID: 1740e8e4c56c
Revises: 
Create Date: 2023-12-06 17:05:36.902711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1740e8e4c56c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('thrown_on_the_floor', sa.Boolean(), nullable=True),
    sa.Column('negotiated', sa.Boolean(), nullable=True),
    sa.Column('placed_in_the_warehouse', sa.Boolean(), nullable=True),
    sa.Column('stored_in_cart', sa.Boolean(), nullable=True),
    sa.Column('sold_to_npc', sa.Boolean(), nullable=True),
    sa.Column('placed_in_the_guild_warehouse', sa.Boolean(), nullable=True),
    sa.Column('drop_from_monster_id', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('obtained_from_id', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_table('monsters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('monster_property', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('base_exp', sa.Integer(), nullable=True),
    sa.Column('class_exp', sa.Integer(), nullable=True),
    sa.Column('resistence_neutral', sa.Integer(), nullable=True),
    sa.Column('resistence_earth', sa.Integer(), nullable=True),
    sa.Column('resistence_wind', sa.Integer(), nullable=True),
    sa.Column('resistence_holy', sa.Integer(), nullable=True),
    sa.Column('resistence_ghost', sa.Integer(), nullable=True),
    sa.Column('resistence_water', sa.Integer(), nullable=True),
    sa.Column('resistence_fire', sa.Integer(), nullable=True),
    sa.Column('resistence_poison', sa.Integer(), nullable=True),
    sa.Column('resistence_dark', sa.Integer(), nullable=True),
    sa.Column('resistence_curse', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('attack_min', sa.Integer(), nullable=True),
    sa.Column('attack_max', sa.Integer(), nullable=True),
    sa.Column('attack_range', sa.Integer(), nullable=True),
    sa.Column('precision', sa.Integer(), nullable=True),
    sa.Column('dodge', sa.Integer(), nullable=True),
    sa.Column('attribute_def', sa.Integer(), nullable=True),
    sa.Column('attribute_defm', sa.Integer(), nullable=True),
    sa.Column('attribute_for', sa.Integer(), nullable=True),
    sa.Column('attribute_agi', sa.Integer(), nullable=True),
    sa.Column('attribute_vit', sa.Integer(), nullable=True),
    sa.Column('attribute_int', sa.Integer(), nullable=True),
    sa.Column('attribute_des', sa.Integer(), nullable=True),
    sa.Column('attribute_sor', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monsters_id'), 'monsters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monsters_id'), table_name='monsters')
    op.drop_table('monsters')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
