"""Add drop to monsters

Revision ID: 2d9097bc6c53
Revises: 1740e8e4c56c
Create Date: 2023-12-09 13:19:00.594053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9097bc6c53'
down_revision: Union[str, None] = '1740e8e4c56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('name', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('drop_items_id', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monsters', 'drop_items_id')
    op.drop_column('monsters', 'name')
    # ### end Alembic commands ###
