"""Add equipments

Revision ID: 366d34859af5
Revises: 07b518539437
Create Date: 2023-12-10 09:41:01.259322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '366d34859af5'
down_revision: Union[str, None] = '07b518539437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('thrown_on_the_floor', sa.Boolean(), nullable=True),
    sa.Column('negotiated', sa.Boolean(), nullable=True),
    sa.Column('placed_in_the_warehouse', sa.Boolean(), nullable=True),
    sa.Column('stored_in_cart', sa.Boolean(), nullable=True),
    sa.Column('sold_to_npc', sa.Boolean(), nullable=True),
    sa.Column('placed_in_the_guild_warehouse', sa.Boolean(), nullable=True),
    sa.Column('drop_from_monster_id', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('obtained_from_id', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipments_id'), 'equipments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipments_id'), table_name='equipments')
    op.drop_table('equipments')
    # ### end Alembic commands ###
